---
- hosts: traffic_gen
  become: yes
  tasks:
    - set_fact:
       measure_id: "{{ measure_id }}"    
    - set_fact:
       subscribers: "{{ range }}"
    - set_fact:
       label: "{{ label }}"
    - set_fact:
       dest_dir: "output/{{ label }}/{{ subscribers }}/{{ measure_id }}/"

    - name: Copy test file to server
      copy:
        src: bng_flow_stats.py
        dest:  /opt/trex/v3.02/automation/trex_control_plane/interactive/trex/examples/stl/

    - name: Copy traffic profile to server
      template:
        src: traffic_profiles.ini
        dest:  /opt/trex/v3.02/

    - name: restart trex-server
      systemd:
        name: trex-server
        state: restarted
      async: 100000
      poll: 0

    - name: let trex start
      pause:
        seconds: 15

    - name: start traffic
      # TOS=> DSCP:START:PPS
      command: "python3 automation/trex_control_plane/interactive/trex/examples/stl/bng_flow_stats.py --tos 12:0:10000 --tos 13:0:10000 --tos 0:10:5000 --results {{ measure_id }} --packet {{ packet_size }} --duration 60 --subscribers {{ subscribers }}"
      async: 100000
      poll: 0
      args:
        chdir: /opt/trex/v3.02/

    - name: let test start
      pause:
        seconds: 20


    - name: Copy trex results
      become: yes
      fetch: 
        src: "/opt/trex/v2.99/results/{{ measure_id }}/trex_results.json"
        dest: "{{ dest_dir }}"
        flat: yes
