---
- hosts: pasta
  tasks:
    - include: start_p4sta.playbook.yml

    - name: let p4sta start
      pause:
        seconds: 10

    - name: Start external host
      shell: "curl http://s9180.labshared.bisdn.de:9997/api/start_external"
      register: url

    - set_fact:
       measure_id: '{{ url.stdout | regex_replace("[^0-9]", "") }}'

    - debug:
        msg: "{{ measure_id }}"

- hosts: traffic_gen
  become: yes
  tasks:
    - set_fact:
       measure_id: "{{ hostvars['s9180.labshared.bisdn.de'].measure_id }}"    

    - set_fact:
       subscribers: 1

    - set_fact:
       accelerator: "vpp"

    - set_fact:
       packet_size: 256

    - name: restart trex-server
      systemd:
        name: trex-server
        state: restarted
      async: 100000
      poll: 0

    - name: Copy test file to server
      copy:
        src: bng_flow_stats.py
        dest:  /opt/trex/v2.99/automation/trex_control_plane/interactive/trex/examples/stl/

    - name: let trex start
      pause:
        seconds: 15

    - name: start traffic
      # TOS=> DSCP:START:PPS
      command: "python3 automation/trex_control_plane/interactive/trex/examples/stl/bng_flow_stats.py --tos 12:0:10000 --tos 13:0:10000 --tos 0:10:5000 --results {{ measure_id }} --packet {{ packet_size }} --duration 60 --subscribers {{ subscribers }}"
      async: 100000
      poll: 0
      args:
        chdir: /opt/trex/v2.99/

    - name: let test start
      pause:
        seconds: 20

- hosts: pasta
  tasks:
    - name: Create log file
      file:
       dest:  "/home/ubuntu/P4STA/results/{{ measure_id }}/power_{{ measure_id }}.csv"
       state: touch

    # - name: run node script
    #   command: node get_power_read.js
    #   register: out
    #   args:
    #     chdir: "/home/ubuntu/"

    - name: let test finish
      pause:
        seconds: 40

          # - lineinfile:
          #    path:  "/home/ubuntu/P4STA/results/{{ measure_id }}/power_{{ measure_id }}.csv"
          #    line: "{{ out.stdout_lines[1] }}"
          #    insertbefore: EOF

    - name: stop external host
      command: curl http://s9180.labshared.bisdn.de:9997/api/stop_external
      register: url

    - set_fact:
       dest_dir: "hqos-measurements/{{ hostvars['waldorf.labshared.bisdn.de'].accelerator }}/{{ hostvars['waldorf.labshared.bisdn.de'].subscribers }}/{{ hostvars['waldorf.labshared.bisdn.de'].packet_size }}/{{ measure_id }}/"

    - name: Sync all files
      pause:
        seconds: 40

    - debug:
        msg: "/home/ubuntu/P4STA/results/{{ measure_id }}/tos_timestamp_list_{{ measure_id }}.csv"

    - name: Copy tos timestamp results
      fetch:
        src: "/home/ubuntu/P4STA/results/{{ measure_id }}/tos_timestamp_list_{{ measure_id }}.csv"
        dest: "{{ dest_dir }}"
        flat: yes

    - name: Copy power results
      fetch:
        src: "/home/ubuntu/P4STA/results/{{ measure_id }}/stamper_{{ measure_id }}.json"
        dest: "{{ dest_dir }}"
        flat: yes

    - name: Copy stamper results
      fetch:
        src: "/home/ubuntu/P4STA/results/{{ measure_id }}/power_{{ measure_id }}.csv"
        dest: "{{ dest_dir }}"
        flat: yes

- hosts: traffic_gen
  tasks:
    - set_fact:
       dest_dir: "hqos-measurements/{{ hostvars['waldorf.labshared.bisdn.de'].accelerator }}/{{ hostvars['waldorf.labshared.bisdn.de'].subscribers }}/{{ hostvars['waldorf.labshared.bisdn.de'].packet_size }}/{{ measure_id }}/"

    - name: Copy trex results
      become: yes
      fetch: 
        src: "/opt/trex/v2.99/results/{{ measure_id }}/trex_results.json"
        dest: "{{ dest_dir }}"
        flat: yes
