---
- hosts: hw_traffic_gen
  become: yes
  tasks:
    - name: Setup loadgen config
      template:
        src: p4tg_post_request.json
        dst: /home/ubuntu/P4TG/p4tg_post_request.json
      vars:
        stream2_rate: "{{ stream2_rate }}"

- hosts: vpp_data_plane
  become: yes
  tasks:
    - name: init VPP
      command: make run-release
      environment:
        STARTUP_CONF: /etc/vpp/startup.conf
