---
- name: Load platform drivers
  command: "bash ./install.sh"
  args:
    chdir: "{{ MILESTONE2 }}/SDE"
  ignore_errors: True

- name: Start kernel driver
  command: "{{ SDE_INSTALL }}/bin/bf_kdrv_mod_load {{ SDE_INSTALL }}"
  ignore_errors: True

- name: Start switchd process
  command: "{{ SDE }}/run_switchd.sh -c /home/ubuntu/p4-dbng-up/basic_mirror/basic_mirror.conf"
  async: 1000000
  poll: 0

- name: Let switch init
  pause:
    seconds: 30

- name: Install forwarding rules
  command: "python3 scripts/redis-mapper.py"
  args:
    chdir: /home/ubuntu/p4-dbng-up
