---
- hosts: tofino_data_plane
  become: yes
  tasks:
    - name: get tofino process
      command: "pgrep bf_switchd"
      register: process

    - name: kill tofino process
      command: "kill {{ processs.stdout }}"


