---
- hosts: traffic_gen
  become: yes
  tasks:
    - name: Copy test file to server
      copy:
        src: incorrect_delay.py
        dest:  /opt/trex/v3.02/automation/trex_control_plane/interactive/trex/examples/stl/

    - name: Copy test file to server
      copy:
        src: bng_flow_stats.py
        dest:  /opt/trex/v3.02/automation/trex_control_plane/interactive/trex/examples/stl/

    - name: Copy traffic profile to server
      template:
        src: traffic_profiles.ini
        dest:  /opt/trex/v3.02/
      vars:
        packet_size:  "{{ packet_size }}"

- hosts: vpp_data_plane
  become: yes
  tasks:
    - name: init VPP
      command: make run-release
      environment:
        STARTUP_CONF: /etc/vpp/startup.conf
      args:
        chdir: /home/ubuntu/bisdn-vpp

    - name: let vpp start
      pause:
        seconds: 10
        
        # - name: init perfcollect
        #   shell: "./perf-collect -p `pgrep vpp` -o /root/perf_hqos/{{ label }}_{{ packet_size }}_{{ measure_id }}.csv &"
        #   async: 1000000
        #   poll: 0
        #   args:
        #     chdir: /root/perfspect
