---
- hosts: traffic_gen
  become: yes
  tasks:
    - set_fact:
       measure_id: "{{ measure_id }}"    
    - set_fact:
       subscribers: "{{ range }}"
    - set_fact:
       label: "{{ label }}"
    - set_fact:
       packet_size: "{{ packet_size }}"
    - set_fact:
       mult: "{{ mult }}"
    - set_fact:
       dest_dir: "../output/{{ label }}/{{ subscribers }}/{{ packet_size }}/{{ measure_id }}/"

    - name: restart trex-server
      systemd:
        name: trex-server
        state: restarted
      async: 100000
      poll: 0

    - name: let trex start
      pause:
        seconds: 30

    - name: start traffic
      # TOS=> DSCP:START:PPS
      command: "./ndr --stl --ports 0 1 --profile automation/trex_control_plane/interactive/trex/examples/stl/bng_flow_stats.py  --prof-tun=subscribers={{ subscribers }},results={{ measure_id }} --force-map -o results/{{ label }}/{{subscribers }}/{{ packet_size }}/{{ measure_id }}/trex_ndr.json"
      args:
        chdir: /opt/trex/v3.02/

    - name: Copy trex results
      become: yes
      fetch: 
        src: "/opt/trex/v3.02/results/{{ label }}/{{subscribers }}/{{ packet_size }}/{{ measure_id }}/trex_ndr.json"
        dest: "{{ dest_dir }}"
        flat: yes

- hosts: vpp_data_plane
  become: yes
  tasks:
    - set_fact:
       measure_id: "{{ measure_id }}"    
    - set_fact:
       subscribers: "{{ range }}"
    - set_fact:
       label: "{{ label }}"
    - set_fact:
       packet_size: "{{ packet_size }}"
    - set_fact:
       dest_dir: "../output/{{ label }}/{{ subscribers }}/{{ packet_size }}/{{ measure_id }}/"

    - name: print vpp stats after test
      command: /root/bisdn-vpp/build-root/build-vpp-native/vpp/bin/vpp_get_stats dump
      register: vppstats

    - name: create stats file
      file: 
        state: touch
        path: /home/ubuntu/vpp/results/{{ measure_id }}_vpp_stats

    - name: output results
      copy:
        content: "{{ vppstats.stdout }}"
        dest: /home/ubuntu/vpp/results/{{ measure_id }}_vpp_stats

    - name: pause stats
      pause:
        seconds: 3

    - name: copy stats file
      become: yes
      fetch: 
        src: "/home/ubuntu/vpp/results/{{ measure_id }}_vpp_stats"
        dest: "{{ dest_dir }}"
        flat: yes

